.Dd 17 April, 2016
.Dt UREDIR 1 
.Os
.Sh NAME
.Nm uredir
.Nd UDP port redirector
.Sh SYNOPSIS
.Nm
.Op Fl hinsv
.Op Fl l Ar LEVEL
.Op Ar SRC:PORT
.Op Ar DST:PORT
.Sh DESCRIPTION
.Nm
is a small tool to redirect UDP traffic.  It can be used as a poor man's
filtering tool, e.g. for small multihomed embedded systems without a
built-in firewall.
.Pp
.Nm
forwards packets to a specified destination remembering the sender's
address, any packets received from the destination are in turn forwarded
to the sender.
.Pp
When
.Nm
is launched from
.Xr inetd 8
it does not immediately exit when the first reply has been forwarded.
Instead it lingers for three (3) seconds in case more requests are
received, e.g. in the case of an SNMP walk.  This helps conserve
precious system resources, useful in particular on embedded systems.
.Pp
For a TCP port redirector, try
.Xr redir 1 ,
which now has the same maintainer as
.Xr uredir 1 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Print a summary of the options and exit
.It Fl i
Run in inetd mode, read data from stdin
.It Fl l Ar LVL
Set log level: none, err, info, notice (default), debug
.It Fl n
Run in foreground, do not detach from controlling terminal
.It Fl s
Use syslog, even if running in foreground, default w/o
.Fl n
.It Fl v
Show program version
.It Ar SRC:PORT
Source IP and UDP port to bind to, use 0.0.0.0 to bind to `INADDR_ANY`
.It Ar DST:PORT
Destination IP and UDP port to redirect to.
.El
.Sh EXAMPLE
.Nf
.Rs
        uredir 0.0.0.0:53 192.168.0.1:53
.Re
.Pp
To run
.Nm
in inetd mode, e.g. to redirect SNMP requests, try the following:
.Pp
.Rs
        snmp dgram udp wait root uredir -n -s -i 127.0.0.1:16161
.Re
.Pp
Syntax may vary between different inetd implementations and UNIX
distributions.
.Fi
.Sh SEE ALSO
.Xr redir 1
.Xr inetd 8
.Sh BUGS
Use the project's GitHub page to file bug reports, feature requests or
patches -- preferably as pull requests
.Aq https://github.com/troglobit/uredir
.Sh AUTHORS
.Nm
is a complete rewrite of
.Nm udp_redirect ,
made by Ivan Tikhonov.  Current maintainer is Joachim Nilsson.
