.Dd 17 April, 2016
.Dt UREDIR 1 
.Os
.Sh NAME
.Nm uredir
.Nd UDP port redirector
.Sh SYNOPSIS
.Nm
.Op Fl hinsv
.Op Fl I Ar ID
.Op Fl l Ar LVL
.Op Fl t Ar SEC
.Op Ar SRC:PORT
.Ar DST:PORT
.Sh DESCRIPTION
.Nm
is a small tool to redirect UDP traffic.  It can be used as a poor man's
filtering tool, e.g. for small multihomed embedded systems without a
built-in firewall.
.Pp
.Nm
forwards packets to a specified destination remembering the sender's
address, any packets received from the destination are in turn forwarded
to the sender.
.Pp
When
.Nm
is launched from
.Xr inetd 8
it does not immediately exit when the first reply has been forwarded.
Instead it lingers for three (3) seconds in case more requests are
received, e.g. in the case of an SNMP walk.  This helps conserve
precious system resources, useful in particular on embedded systems.
.Pp
For a TCP port redirector, try
.Xr redir 1 ,
which now has the same maintainer as
.Xr uredir 1 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Print a summary of the options and exit
.It Fl i
Run in inetd mode, read data from stdin.  Implies
.Fl n ,
always runs in foreground
.It Fl I Ar ID
Identity, tag syslog messages with the ID name, default: process name
.It Fl l Ar LVL
Set log level: none, err, info, notice (default), debug
.It Fl n
Run in foreground, do not detach from controlling terminal
.It Fl s
Use syslog, even if running in foreground, default w/o
.Fl n
.It Fl t Ar SEC
Set timeout to SEC seconds for inetd connections, default 3
.It Fl v
Show program version
.It Ar SRC:PORT
Source IP and UDP port to bind to, the SRC can be left out to default to
0.0.0.0.  Must not be set when running in
.Fl i ,
inetd mode
.It Ar DST:PORT
Destination IP and UDP port to redirect to
.El
.Sh EXAMPLE
This simple UDP proxy example forwards inbound DNS requests on any
interface to an external DNS server on 192.168.0.1.
.Pp
.Rs
        uredir :53 192.168.0.1:53
.Re
.Pp
To run
.Nm
in inetd mode, e.g. to redirect SNMP requests, and timeout after 5 sec,
try the following.  Runs in foreground, as required for inetd services,
and uses syslog for logging:
.Pp
.Rs
        snmp dgram udp wait root uredir -it 5 127.0.0.1:16161
.Re
.Pp
Syntax may vary between different inetd implementations and UNIX
distributions.
.Fi
.Sh SEE ALSO
.Xr redir 1
.Xr inetd 8
.Sh BUGS
Use the project's GitHub page to file bug reports, feature requests or
patches -- preferably as pull requests
.Aq https://github.com/troglobit/uredir
.Sh AUTHORS
.Nm
used to be based on
.Nm udp_redirect
by Ivan Tikhonov, but is today based on youdp by Tobias Waldekranz.
Current maintainer is Joachim Nilsson.
