name: Bob the Builder

# Run on all branches, including all pull requests, except the 'dev'
# branch since that's where we run Coverity Scan (limited tokens/day)
on:
  push:
    branches:
      - '**'
      - '!dev'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    env:
      MAKEFLAGS: -j3
      CC: ${{ matrix.compiler }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install tree
          wget https://github.com/troglobit/libuev/releases/download/v2.3.2/libuev-2.3.2.tar.xz
          tar xf libuev-2.3.2.tar.xz
          (cd libuev-2.3.2 && ./configure --prefix=/usr && make && sudo make install-strip)
          sudo ldconfig
      - uses: actions/checkout@v3
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=
      - name: Build
        run: |
          make V=1
      - name: Install
        run: |
          DESTDIR=~/tmp make install-strip
          tree ~/tmp
          ldd ~/tmp/bin/uredir
          size ~/tmp/bin/uredir
          ~/tmp/bin/uredir -h
  debian:
    # Verify that Debian packages can be built
    name: Debian Package
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - uses: actions/checkout@v3
      - name: Installing dependencies
        run: |
          apt-get -y update
          apt-get install -y build-essential autoconf automake dpkg-dev debhelper \
                             devscripts libsystemd-dev systemd pkg-config curl
          curl -sS https://deb.troglobit.com/pubkey.gpg | apt-key add -
          echo "deb [arch=amd64] https://deb.troglobit.com/debian stable main" \
               | tee /etc/apt/sources.list.d/troglobit.list
          apt-get -y update
          apt-get install -y libuev-dev
      - name: Building Debian package
        run: |
          ./autogen.sh
          ./configure
          make distcheck
          make package

